// <auto-generated />
using System;
using CagriMerkeziAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CagriMerkeziAPI.Migrations
{
    [DbContext(typeof(CagriMerkeziContext))]
    partial class CagriMerkeziContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CagriMerkeziAPI.Models.CagriDetay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("cagriTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("konu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("musteriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("servisElemanı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sonuc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("CagriDetays");
                });
#pragma warning restore 612, 618
        }
    }
}
